import type { PropTable, PropRow } from './registry'

const rows = (...items: [string, string, string | undefined, string][]): PropRow[] => items.map(([name, type, defaultValue, description]) => ({ name, type, ...(defaultValue === undefined ? {} : { default: defaultValue }), description }))
const table = (heading: string, data: PropRow[]): PropTable => ({ heading, rows: data })

export const PROPS: Record<string, PropTable[]> = {
  'tag-input-field': [table('TagInputField Props', rows(
    ['label', 'string', undefined, '输入框标签。'],
    ['values', 'string[]', undefined, '已提交的标签列表。'],
    ['draft', 'string', undefined, '当前输入内容。'],
    ['onDraftChange', '(raw: string) => void', undefined, '更新输入内容。'],
    ['onAdd', '() => void', undefined, '提交新增标签，由调用方校验并更新 values。'],
    ['onRemove', '(value: string, index: number) => void', undefined, '移除指定标签。'],
    ['onUpdate', '(value: string, index: number, nextValue: string) => boolean | void', undefined, '编辑标签；返回 false 时保留编辑状态。'],
    ['addLabel', 'string', '添加', '添加按钮的可访问名称。'],
    ['placeholder', 'string', undefined, '输入框占位文案。'],
    ['hint', 'string', undefined, '辅助说明。'],
    ['errorText', 'string', undefined, '校验错误，优先于 hint 显示。'],
    ['disabled', 'boolean', 'false', '禁用输入与标签操作。'],
    ['maxLength', 'number', undefined, '新增及编辑输入框的最大字符数。'],
    ['onBlur', '() => void', undefined, '新增输入框失焦时触发。'],
  ))],
  'settings-action-row': [table('SettingsActionRow Props', rows(
    ['title', 'string', undefined, '设置项标题。'],
    ['description', 'ReactNode', undefined, '设置项说明。'],
    ['icon', 'string', undefined, '前置图标。'],
    ['status', 'ReactNode', undefined, '状态标记。'],
    ['actions', 'ReactNode', undefined, '操作区，在窄屏中纵向排列。'],
    ['accent', "'cyan' | 'gold'", 'cyan', '图标语义色。'],
    ['className', 'string', undefined, '追加容器样式。'],
  ))],
  'session-item': [table('SessionItem Props', rows(
    ['icon', 'string', 'monitor', '设备图标名称。'],
    ['title', 'string', undefined, '设备或会话标题。'],
    ['status', 'ReactNode', undefined, '认证状态标记。'],
    ['description', 'ReactNode', undefined, '地点、最近活动等辅助信息。'],
    ['actions', 'ReactNode', undefined, '会话操作区，在窄屏中纵向铺满。'],
    ['className', 'string', undefined, '追加容器样式。'],
  ))],
  'brand-mark': [table('BrandMark Props', rows(['className', 'string', 'h-8 w-8', '自定义 Logo 尺寸和样式。'], ['decorative', 'boolean', 'false', '是否对辅助技术隐藏品牌名称。']))],
  'flow-gold-text': [table('FlowGoldText Props', rows(['children', 'ReactNode', undefined, '要显示的品牌文字。'], ['as', "'span' | 'strong' | 'p' | 'div' | 'h1' | 'h2' | 'h3'", 'span', '选择语义 HTML 根元素。'], ['animated', 'boolean', 'true', '是否播放流金扫光；系统开启减少动态效果时自动静止。'], ['className', 'string', undefined, '追加字号、间距等样式。']))],
  'brand-lockup': [table('BrandLockup Props', rows(['subtitle', 'string', '辰星认证中枢', 'Logo 下方的副标题。'], ['compact', 'boolean', 'false', '切换为顶栏紧凑版式。']))],
  button: [table('Button Props', rows(['children', 'ReactNode', undefined, '按钮内容。'], ['variant', "'primary' | 'ghost' | 'danger'", 'primary', '按钮的语义和视觉变体。'], ['icon', 'string', undefined, '前置 lucide 图标名称。'], ['aria-disabled', 'boolean | string', undefined, '保持可聚焦的逻辑禁用状态。'], ['className', 'string', undefined, '追加按钮样式。']))],
  badge: [table('Badge Props', rows(['children', 'ReactNode', undefined, '徽章内容。'], ['tone', "'neutral' | 'success' | 'warning' | 'gold'", 'neutral', '徽章的语义色调。']))],
  chip: [table('Chip Props', rows(['children', 'ReactNode', undefined, '标签内容。'], ['color', "'default' | 'accent' | 'success' | 'warning' | 'danger'", 'default', '标签颜色。'], ['onRemove', '() => void', undefined, '存在时显示可访问的移除按钮。']))],
  icon: [table('Icon Props', rows(['name', 'string', undefined, 'lucide 图标的语义名称。'], ['size', 'number', '16', '图标的像素尺寸。'], ['strokeWidth', 'number', '1.8', '描边宽度。'], ['className', 'string', undefined, '追加 SVG 样式。']))],
  notice: [table('Notice Props', rows(['children', 'ReactNode', undefined, '通知正文。'], ['tone', "'info' | 'success' | 'warning'", 'info', '通知语气，同时决定 aria-live。']))],
  avatar: [table('Avatar Props', rows(['src', 'string', undefined, '头像图片地址。'], ['name', 'string | null', undefined, '头像名称，用于组件 API 对齐。'], ['className', 'string', undefined, '追加容器样式。']))],
  'copy-value': [table('CopyValue Props', rows(['value', 'string', undefined, '需要展示并复制的值。'], ['ariaLabel', 'string', '复制值', '复制按钮的辅助技术名称。'], ['announceValue', 'boolean', 'false', '是否在无障碍名称中读出完整值。']))],
  'empty-state': [table('EmptyState Props', rows(['icon', 'string', 'sparkles', '空状态图标名称。'], ['title', 'string', undefined, '空状态标题。'], ['description', 'string', undefined, '补充说明。'], ['action', 'ReactNode', undefined, '引导操作。']))],
  'page-intro': [table('PageIntro Props', rows(['eyebrow', 'string', undefined, '标题上方的分类标签。'], ['title', 'string', undefined, '页面主标题。'], ['description', 'string', undefined, '页面说明。'], ['action', 'ReactNode', undefined, '右侧操作区。']))],
  field: [table('Field Props', rows(['label', 'string', undefined, '输入框标签。'], ['icon', 'string', undefined, '前置图标名称。'], ['hint', 'string', undefined, '辅助说明文本。'], ['error', 'boolean', undefined, '是否应用错误样式。'], ['errorText', 'string', undefined, '错误文案，同时关联 aria-describedby。'], ['trailing', 'ReactNode', undefined, '输入框尾随内容。']))],
  'password-field': [table('PasswordField Props', rows(['label', 'string', undefined, '输入框标签。'], ['icon', 'string', undefined, '前置图标名称。'], ['hint', 'string', undefined, '辅助说明文本。'], ['errorText', 'string', undefined, '错误文案。']))],
  'text-area-field': [table('TextAreaField Props', rows(['label', 'string', undefined, '文本域标签。'], ['hint', 'string', undefined, '辅助说明文本。'], ['error', 'boolean', undefined, '是否应用错误样式。'], ['errorText', 'string', undefined, '错误文案。']))],
  select: [table('Select Props', rows(['value', 'string', undefined, '当前选中值。'], ['onChange', '(value: string) => void', undefined, '值变化回调。'], ['options', 'SelectOption[]', undefined, '选项列表。'], ['disabled', 'boolean', 'false', '是否禁用选择器。'], ['placeholder', 'string', '请选择', '无选中值时显示的文案。'])), table('SelectOption', rows(['value', 'string', undefined, '选项值。'], ['label', 'string', undefined, '选项显示文本。'], ['disabled', 'boolean', undefined, '是否禁用该选项。']))],
  'select-field': [table('SelectField Props', rows(['label', 'string', undefined, '选择器标签。'], ['icon', 'string', undefined, '前置图标名称。'], ['hint', 'string', undefined, '辅助说明文本。'], ['options', 'SelectOption[]', undefined, '选项列表。']))],
  switch: [table('Switch Props', rows(['checked', 'boolean', undefined, '当前开关状态。'], ['onChange', '(checked: boolean) => void', undefined, '状态变化回调。'], ['disabled', 'boolean', 'false', '是否禁用。'], ['label', 'string', undefined, '辅助技术标签。']))],
  'toggle-row': [table('ToggleRow Props', rows(['title', 'string', undefined, '设置项标题。'], ['description', 'string', undefined, '设置项说明。'], ['checked', 'boolean', undefined, '当前状态。'], ['onChange', '(checked: boolean) => void', undefined, '状态变化回调。'], ['disabled', 'boolean', 'false', '是否禁用。']))],
  'field-shell': [table('FieldShell Props', rows(['icon', 'string', undefined, '前置图标名称。'], ['trailing', 'ReactNode', undefined, '尾随内容。'], ['error', 'boolean', undefined, '是否应用错误边框。'], ['children', 'ReactNode', undefined, '内部表单控件。']))],
  'search-field': [table('SearchField Props', rows(['onSearch', '() => void', undefined, '按 Enter 时触发搜索。'], ['shellClassName', 'string', 'w-full sm:w-72', '搜索外壳宽度样式。'], ['placeholder', 'string', undefined, '输入框占位文案。']))],
  'hud-panel': [table('HudPanel Props', rows(['as', "'div' | 'section' | 'article' | 'aside' | 'form'", 'div', '渲染的语义 HTML 标签。'], ['children', 'ReactNode', undefined, '面板内容。'], ['className', 'string', undefined, '追加面板样式。']))],
  table: [table('DataTable Props', rows(['columns', 'DataTableColumn[]', undefined, '表头列定义。'], ['minWidth', 'number', undefined, '触发横向滚动的最小宽度。'], ['empty', 'ReactNode', undefined, '无数据时渲染的内容。'], ['children', 'ReactNode', undefined, '表格行。'])), table('TablePanel Props', rows(['title', 'string', undefined, '表格面板标题。'], ['description', 'string', undefined, '表格说明。'], ['action', 'ReactNode', undefined, '右侧操作区。'], ['notice', 'ReactNode', undefined, '表格上方通知。'])), table('TablePagination Props', rows(['page', 'number', undefined, '当前页码，从 1 开始。'], ['totalPages', 'number', undefined, '总页数。'], ['total', 'number', undefined, '数据总数。'], ['onPageChange', '(page: number) => void', undefined, '翻页回调。']))],
  drawer: [table('Drawer Props', rows(['title', 'string', undefined, '抽屉标题。'], ['description', 'string', undefined, '抽屉说明。'], ['onClose', '() => void', undefined, '关闭回调。'], ['onSubmit', 'FormEventHandler<HTMLFormElement>', undefined, '表单提交回调。'], ['busy', 'boolean', 'false', '忙碌时锁定关闭操作。'], ['footer', 'ReactNode', undefined, '底部操作区。']))],
  'avatar-editor': [table('AvatarEditor Props', rows(['image', 'HTMLImageElement', undefined, '已经解码的源图。'], ['source', 'SourceSize', undefined, '源图尺寸。'], ['busy', 'boolean', 'false', '上传处理状态。'], ['onCancel', '() => void', undefined, '取消回调。'], ['onConfirm', '(blob: Blob) => void', undefined, '导出 PNG 后的回调。']))],
  reveal: [table('Reveal Props', rows(['children', 'ReactNode', undefined, '需要入场的内容。'], ['delay', 'number', '0', '动画延迟毫秒数。'], ['variant', "'rise' | 'mask'", 'rise', '入场动画变体。']))],
  'count-up': [table('CountUp Props', rows(['target', 'number', undefined, '目标数值。'], ['decimals', 'number', '0', '小数位数。'], ['suffix', 'string', undefined, '数值后缀。'], ['grouping', 'boolean', 'false', '是否使用千位分隔。'], ['duration', 'number', '1800', '动画时长毫秒数。']))],
  typewriter: [table('Typewriter Props', rows(['words', 'string[]', undefined, '循环显示的词语。'], ['typeMs', 'number', '110', '逐字显示间隔。'], ['eraseMs', 'number', '45', '逐字擦除间隔。'], ['holdMs', 'number', '1800', '完整词语停留时间。']))],
  'scramble-text': [table('ScrambleText Props', rows(['text', 'string', undefined, '待解码文本。'], ['active', 'boolean', undefined, '是否播放解码。']))],
  'draw-line': [table('DrawLine Props', rows(['className', 'string', undefined, '追加分割线样式。']))],
  'warp-field': [table('WarpField Props', rows(['stars', 'number', '200', '星点数量。'], ['className', 'string', undefined, '画布定位和样式。']))],
  'space-backdrop': [table('SpaceBackdrop Props', rows(['children', 'ReactNode', undefined, '页面内容。'], ['opacity', 'number', '0.7', '星场透明度。'], ['dense', 'boolean', 'false', '是否使用密集星场。'], ['className', 'string', undefined, '追加根容器样式。']))],
  'intro-gate': [table('IntroGate Props', rows(['onDone', '() => void', undefined, '动画完成后的回调。']))],
  'skip-link': [table('SkipLink / SkipTarget', rows(['targetId', 'string', undefined, '跳转目标元素 ID。'], ['useSkipTargetId()', '() => string', undefined, '生成稳定的无障碍目标 ID。']))],
  topbar: [table('Topbar Props', rows(['brand', 'ReactNode', undefined, '左侧品牌内容。'], ['status', 'ReactNode', undefined, '中间状态文案。'], ['links', 'readonly { label: string; href: string }[]', undefined, '展开时显示的导航链接。'], ['actions', 'ReactNode', undefined, '右侧操作区。'], ['menu', 'ReactNode', undefined, '汉堡菜单内容。'], ['expandOnTop', 'boolean', 'true', '是否根据页面顶部自动展开。']))],
  'error-boundary': [table('ErrorBoundary Props', rows(['children', 'ReactNode', undefined, '受保护的子树。'], ['homeHref', 'string', '/', '恢复页返回地址。']))],
  toast: [table('ToastProvider Props', rows(['placement', "ToastPlacement", 'bottom-end', '通知堆栈位置。'], ['maxVisible', 'number', '3', '同时可见的最大通知数。'], ['gap', 'number', '12', '通知堆叠间距。'], ['children', 'ReactNode', undefined, '应用内容。'])), table('ToastOptions', rows(['description', 'ReactNode', undefined, '通知补充说明。'], ['tone', 'ToastTone', 'info', '通知语气。'], ['icon', 'string', undefined, '覆盖默认图标。'], ['timeout', 'number', '4000', '自动关闭时间，0 表示常驻。'], ['onClose', '() => void', undefined, '移除后的回调。']))],
}
